### ISSUE TITLE
Add support for Encrypted PDF Files

### ISSUE THREAD

**Issue by kairavkkp** [kairavkkp/Merge-PDF#8]

**Comment by kairavkkp** [comment]
Add support for merging Encrypted PDF or Image Files to be merged.

**Comment by isaacvv** [comment]
Sure, I will take a stab at this. Can you assign to me?

**Comment by kairavkkp** [comment]
Sure @isaacvv Please give it a go!

**Comment by kairavkkp** [comment]
Closing the issue. The solution is in #10.
